/// DimensionValue 시드 데이터 — 5대 분류 기본 트리 + 정부회계 확장.
/// DB 초기화 시 seedDimensionValues()를 호출하여 batch insert.
///
/// Materialized Path 방식: code = 'ASSET.CURRENT.CASH' 형태.
/// 총 노드 수: 약 257개 (가계/기업 공용 L1~L4) + 정부회계 확장 약 10개.
library;

// --- 시드 데이터 레코드 ---

/// 단일 DimensionValue 시드 항목
class _Seed {
  final String type;
  final String code;
  final String name;
  final String? parentCode;
  final String entityType;
  final int sortOrder;

  const _Seed(this.type, this.code, this.name, this.parentCode, this.entityType, this.sortOrder);
}

// =============================================================================
// 1. EQUITY_TYPE (자기자본성) — 5대 분류 전체 트리
// =============================================================================

const List<_Seed> _kEquityTypeSeeds = [
  // --- ASSET (자산) ---
  _Seed('EQUITY_TYPE', 'ASSET', '자산', null, 'COMMON', 100),
  _Seed('EQUITY_TYPE', 'ASSET.CURRENT', '유동자산', 'ASSET', 'COMMON', 110),
  _Seed('EQUITY_TYPE', 'ASSET.CURRENT.CASH', '현금및현금성자산', 'ASSET.CURRENT', 'COMMON', 111),
  // L4: CASH 하위
  _Seed('EQUITY_TYPE', 'ASSET.CURRENT.CASH.CHECKING', '보통예금', 'ASSET.CURRENT.CASH', 'COMMON', 1111),
  _Seed('EQUITY_TYPE', 'ASSET.CURRENT.CASH.SAVINGS_CMA', 'CMA/MMF', 'ASSET.CURRENT.CASH', 'COMMON', 1112),
  _Seed('EQUITY_TYPE', 'ASSET.CURRENT.CASH.HAND', '현금보유', 'ASSET.CURRENT.CASH', 'COMMON', 1113),
  _Seed('EQUITY_TYPE', 'ASSET.CURRENT.CASH.FOREIGN_DEPOSIT', '외화예금', 'ASSET.CURRENT.CASH', 'COMMON', 1114),
  _Seed('EQUITY_TYPE', 'ASSET.CURRENT.SHORT_TERM_FINANCIAL', '단기금융자산', 'ASSET.CURRENT', 'COMMON', 112),
  // L4: 단기금융 하위
  _Seed('EQUITY_TYPE', 'ASSET.CURRENT.SHORT_TERM_FINANCIAL.TIME_DEPOSIT', '정기예금(단기)', 'ASSET.CURRENT.SHORT_TERM_FINANCIAL', 'COMMON', 1121),
  _Seed('EQUITY_TYPE', 'ASSET.CURRENT.SHORT_TERM_FINANCIAL.FVTPL', '단기FVTPL금융자산', 'ASSET.CURRENT.SHORT_TERM_FINANCIAL', 'COMMON', 1122),
  _Seed('EQUITY_TYPE', 'ASSET.CURRENT.SHORT_TERM_FINANCIAL.FVOCI', '단기FVOCI금융자산', 'ASSET.CURRENT.SHORT_TERM_FINANCIAL', 'COMMON', 1123),
  _Seed('EQUITY_TYPE', 'ASSET.CURRENT.SHORT_TERM_FINANCIAL.AMORTIZED_COST', '단기상각후원가금융자산', 'ASSET.CURRENT.SHORT_TERM_FINANCIAL', 'COMMON', 1124),
  _Seed('EQUITY_TYPE', 'ASSET.CURRENT.RECEIVABLE', '매출채권및미수금', 'ASSET.CURRENT', 'COMMON', 113),
  // L4: 채권 하위
  _Seed('EQUITY_TYPE', 'ASSET.CURRENT.RECEIVABLE.TRADE', '매출채권', 'ASSET.CURRENT.RECEIVABLE', 'COMMON', 1131),
  _Seed('EQUITY_TYPE', 'ASSET.CURRENT.RECEIVABLE.OTHER', '미수금', 'ASSET.CURRENT.RECEIVABLE', 'COMMON', 1132),
  _Seed('EQUITY_TYPE', 'ASSET.CURRENT.RECEIVABLE.ACCRUED', '미수수익', 'ASSET.CURRENT.RECEIVABLE', 'COMMON', 1133),
  _Seed('EQUITY_TYPE', 'ASSET.CURRENT.RECEIVABLE.SHORT_TERM_LOAN', '단기대여금', 'ASSET.CURRENT.RECEIVABLE', 'COMMON', 1134),
  _Seed('EQUITY_TYPE', 'ASSET.CURRENT.RECEIVABLE.ALLOWANCE', '대손충당금', 'ASSET.CURRENT.RECEIVABLE', 'COMMON', 1135),
  _Seed('EQUITY_TYPE', 'ASSET.CURRENT.PREPAID', '선급금및선급비용', 'ASSET.CURRENT', 'COMMON', 114),
  // L4: 선급 하위
  _Seed('EQUITY_TYPE', 'ASSET.CURRENT.PREPAID.ADVANCE_PAYMENT', '선급금', 'ASSET.CURRENT.PREPAID', 'COMMON', 1141),
  _Seed('EQUITY_TYPE', 'ASSET.CURRENT.PREPAID.PREPAID_EXPENSE', '선급비용', 'ASSET.CURRENT.PREPAID', 'COMMON', 1142),
  _Seed('EQUITY_TYPE', 'ASSET.CURRENT.PREPAID.PREPAID_TAX', '선급법인세', 'ASSET.CURRENT.PREPAID', 'COMMON', 1143),
  _Seed('EQUITY_TYPE', 'ASSET.CURRENT.INVENTORY', '재고자산', 'ASSET.CURRENT', 'COMMON', 115),
  // L4: 재고 하위
  _Seed('EQUITY_TYPE', 'ASSET.CURRENT.INVENTORY.MERCHANDISE', '상품', 'ASSET.CURRENT.INVENTORY', 'COMMON', 1151),
  _Seed('EQUITY_TYPE', 'ASSET.CURRENT.INVENTORY.FINISHED_GOODS', '제품', 'ASSET.CURRENT.INVENTORY', 'COMMON', 1152),
  _Seed('EQUITY_TYPE', 'ASSET.CURRENT.INVENTORY.RAW_MATERIAL', '원재료', 'ASSET.CURRENT.INVENTORY', 'COMMON', 1153),
  _Seed('EQUITY_TYPE', 'ASSET.CURRENT.INVENTORY.WORK_IN_PROGRESS', '재공품', 'ASSET.CURRENT.INVENTORY', 'COMMON', 1154),
  _Seed('EQUITY_TYPE', 'ASSET.CURRENT.INVENTORY.SUPPLIES', '소모품', 'ASSET.CURRENT.INVENTORY', 'COMMON', 1155),
  _Seed('EQUITY_TYPE', 'ASSET.CURRENT.INVENTORY.ALLOWANCE_NRV', '재고자산평가충당금', 'ASSET.CURRENT.INVENTORY', 'COMMON', 1156),
  _Seed('EQUITY_TYPE', 'ASSET.CURRENT.OTHER', '기타유동자산', 'ASSET.CURRENT', 'COMMON', 116),
  _Seed('EQUITY_TYPE', 'ASSET.NON_CURRENT', '비유동자산', 'ASSET', 'COMMON', 120),
  _Seed('EQUITY_TYPE', 'ASSET.NON_CURRENT.INVESTMENT', '투자자산', 'ASSET.NON_CURRENT', 'COMMON', 121),
  // L4: 투자 하위
  _Seed('EQUITY_TYPE', 'ASSET.NON_CURRENT.INVESTMENT.LONG_TERM_FINANCIAL', '장기금융상품', 'ASSET.NON_CURRENT.INVESTMENT', 'COMMON', 1211),
  _Seed('EQUITY_TYPE', 'ASSET.NON_CURRENT.INVESTMENT.FVTPL', '비유동FVTPL금융자산', 'ASSET.NON_CURRENT.INVESTMENT', 'COMMON', 1212),
  _Seed('EQUITY_TYPE', 'ASSET.NON_CURRENT.INVESTMENT.FVOCI', '비유동FVOCI금융자산', 'ASSET.NON_CURRENT.INVESTMENT', 'COMMON', 1213),
  _Seed('EQUITY_TYPE', 'ASSET.NON_CURRENT.INVESTMENT.AMORTIZED_COST', '비유동상각후원가금융자산', 'ASSET.NON_CURRENT.INVESTMENT', 'COMMON', 1214),
  _Seed('EQUITY_TYPE', 'ASSET.NON_CURRENT.INVESTMENT.ASSOCIATE', '관계기업투자', 'ASSET.NON_CURRENT.INVESTMENT', 'COMMON', 1215),
  _Seed('EQUITY_TYPE', 'ASSET.NON_CURRENT.INVESTMENT.PROPERTY', '투자부동산', 'ASSET.NON_CURRENT.INVESTMENT', 'COMMON', 1216),
  _Seed('EQUITY_TYPE', 'ASSET.NON_CURRENT.TANGIBLE', '유형자산', 'ASSET.NON_CURRENT', 'COMMON', 122),
  // L4: 유형자산 하위 8종
  _Seed('EQUITY_TYPE', 'ASSET.NON_CURRENT.TANGIBLE.LAND', '토지', 'ASSET.NON_CURRENT.TANGIBLE', 'COMMON', 1221),
  _Seed('EQUITY_TYPE', 'ASSET.NON_CURRENT.TANGIBLE.BUILDING', '건물', 'ASSET.NON_CURRENT.TANGIBLE', 'COMMON', 1222),
  _Seed('EQUITY_TYPE', 'ASSET.NON_CURRENT.TANGIBLE.STRUCTURE', '구축물', 'ASSET.NON_CURRENT.TANGIBLE', 'COMMON', 1223),
  _Seed('EQUITY_TYPE', 'ASSET.NON_CURRENT.TANGIBLE.MACHINERY', '기계장치', 'ASSET.NON_CURRENT.TANGIBLE', 'COMMON', 1224),
  _Seed('EQUITY_TYPE', 'ASSET.NON_CURRENT.TANGIBLE.FURNITURE', '집기비품', 'ASSET.NON_CURRENT.TANGIBLE', 'COMMON', 1225),
  _Seed('EQUITY_TYPE', 'ASSET.NON_CURRENT.TANGIBLE.VEHICLE', '차량운반구', 'ASSET.NON_CURRENT.TANGIBLE', 'COMMON', 1226),
  _Seed('EQUITY_TYPE', 'ASSET.NON_CURRENT.TANGIBLE.CONSTRUCTION_IN_PROGRESS', '건설중인자산', 'ASSET.NON_CURRENT.TANGIBLE', 'COMMON', 1227),
  _Seed('EQUITY_TYPE', 'ASSET.NON_CURRENT.TANGIBLE.OTHER', '기타유형자산', 'ASSET.NON_CURRENT.TANGIBLE', 'COMMON', 1228),
  _Seed('EQUITY_TYPE', 'ASSET.NON_CURRENT.INTANGIBLE', '무형자산', 'ASSET.NON_CURRENT', 'COMMON', 123),
  // L4: 무형자산 하위 5종
  _Seed('EQUITY_TYPE', 'ASSET.NON_CURRENT.INTANGIBLE.GOODWILL', '영업권', 'ASSET.NON_CURRENT.INTANGIBLE', 'COMMON', 1231),
  _Seed('EQUITY_TYPE', 'ASSET.NON_CURRENT.INTANGIBLE.INDUSTRIAL_PROPERTY', '산업재산권', 'ASSET.NON_CURRENT.INTANGIBLE', 'COMMON', 1232),
  _Seed('EQUITY_TYPE', 'ASSET.NON_CURRENT.INTANGIBLE.SOFTWARE', '소프트웨어', 'ASSET.NON_CURRENT.INTANGIBLE', 'COMMON', 1233),
  _Seed('EQUITY_TYPE', 'ASSET.NON_CURRENT.INTANGIBLE.MEMBERSHIP', '회원권', 'ASSET.NON_CURRENT.INTANGIBLE', 'COMMON', 1234),
  _Seed('EQUITY_TYPE', 'ASSET.NON_CURRENT.INTANGIBLE.OTHER', '기타무형자산', 'ASSET.NON_CURRENT.INTANGIBLE', 'COMMON', 1235),
  _Seed('EQUITY_TYPE', 'ASSET.NON_CURRENT.OTHER', '기타비유동자산', 'ASSET.NON_CURRENT', 'COMMON', 124),
  // L4: 기타비유동 하위
  _Seed('EQUITY_TYPE', 'ASSET.NON_CURRENT.OTHER.LONG_TERM_LOAN', '장기대여금', 'ASSET.NON_CURRENT.OTHER', 'COMMON', 1241),
  _Seed('EQUITY_TYPE', 'ASSET.NON_CURRENT.OTHER.LEASE_DEPOSIT', '임차보증금', 'ASSET.NON_CURRENT.OTHER', 'COMMON', 1242),
  _Seed('EQUITY_TYPE', 'ASSET.NON_CURRENT.OTHER.LONG_TERM_RECEIVABLE', '장기미수금', 'ASSET.NON_CURRENT.OTHER', 'COMMON', 1243),
  _Seed('EQUITY_TYPE', 'ASSET.NON_CURRENT.OTHER.DEFERRED_TAX_ASSET', '이연법인세자산', 'ASSET.NON_CURRENT.OTHER', 'COMMON', 1244),

  // --- LIABILITY (부채) ---
  _Seed('EQUITY_TYPE', 'LIABILITY', '부채', null, 'COMMON', 200),
  _Seed('EQUITY_TYPE', 'LIABILITY.CURRENT', '유동부채', 'LIABILITY', 'COMMON', 210),
  _Seed('EQUITY_TYPE', 'LIABILITY.CURRENT.PAYABLE', '미지급금및미지급비용', 'LIABILITY.CURRENT', 'COMMON', 211),
  // L4: 미지급 하위
  _Seed('EQUITY_TYPE', 'LIABILITY.CURRENT.PAYABLE.TRADE', '매입채무', 'LIABILITY.CURRENT.PAYABLE', 'COMMON', 2111),
  _Seed('EQUITY_TYPE', 'LIABILITY.CURRENT.PAYABLE.OTHER', '미지급금', 'LIABILITY.CURRENT.PAYABLE', 'COMMON', 2112),
  _Seed('EQUITY_TYPE', 'LIABILITY.CURRENT.PAYABLE.ACCRUED', '미지급비용', 'LIABILITY.CURRENT.PAYABLE', 'COMMON', 2113),
  _Seed('EQUITY_TYPE', 'LIABILITY.CURRENT.SHORT_TERM_BORROWING', '단기차입금', 'LIABILITY.CURRENT', 'COMMON', 212),
  // L4: 단기차입 하위
  _Seed('EQUITY_TYPE', 'LIABILITY.CURRENT.SHORT_TERM_BORROWING.BANK_LOAN', '은행대출(단기)', 'LIABILITY.CURRENT.SHORT_TERM_BORROWING', 'COMMON', 2121),
  _Seed('EQUITY_TYPE', 'LIABILITY.CURRENT.SHORT_TERM_BORROWING.CURRENT_PORTION', '유동성장기차입금', 'LIABILITY.CURRENT.SHORT_TERM_BORROWING', 'COMMON', 2122),
  _Seed('EQUITY_TYPE', 'LIABILITY.CURRENT.WITHHOLDING', '예수금', 'LIABILITY.CURRENT', 'COMMON', 213),
  _Seed('EQUITY_TYPE', 'LIABILITY.CURRENT.ADVANCE', '선수금', 'LIABILITY.CURRENT', 'COMMON', 214),
  _Seed('EQUITY_TYPE', 'LIABILITY.CURRENT.CARD_PAYABLE', '카드미지급금', 'LIABILITY.CURRENT', 'COMMON', 215),
  _Seed('EQUITY_TYPE', 'LIABILITY.CURRENT.TAX_PAYABLE', '미지급법인세', 'LIABILITY.CURRENT', 'COMMON', 216),
  _Seed('EQUITY_TYPE', 'LIABILITY.CURRENT.PROVISION', '유동충당부채', 'LIABILITY.CURRENT', 'COMMON', 217),
  // L4: 충당부채 하위
  _Seed('EQUITY_TYPE', 'LIABILITY.CURRENT.PROVISION.WARRANTY', '제품보증충당', 'LIABILITY.CURRENT.PROVISION', 'COMMON', 2171),
  _Seed('EQUITY_TYPE', 'LIABILITY.CURRENT.PROVISION.LITIGATION', '소송충당', 'LIABILITY.CURRENT.PROVISION', 'COMMON', 2172),
  _Seed('EQUITY_TYPE', 'LIABILITY.CURRENT.PROVISION.POINTS', '포인트충당', 'LIABILITY.CURRENT.PROVISION', 'COMMON', 2173),
  _Seed('EQUITY_TYPE', 'LIABILITY.CURRENT.PROVISION.RETURNS', '반품충당', 'LIABILITY.CURRENT.PROVISION', 'COMMON', 2174),
  _Seed('EQUITY_TYPE', 'LIABILITY.CURRENT.PROVISION.OTHER', '기타충당', 'LIABILITY.CURRENT.PROVISION', 'COMMON', 2175),
  _Seed('EQUITY_TYPE', 'LIABILITY.CURRENT.OTHER', '기타유동부채', 'LIABILITY.CURRENT', 'COMMON', 218),
  _Seed('EQUITY_TYPE', 'LIABILITY.NON_CURRENT', '비유동부채', 'LIABILITY', 'COMMON', 220),
  _Seed('EQUITY_TYPE', 'LIABILITY.NON_CURRENT.LONG_TERM_BORROWING', '장기차입금', 'LIABILITY.NON_CURRENT', 'COMMON', 221),
  // L4: 장기차입 하위
  _Seed('EQUITY_TYPE', 'LIABILITY.NON_CURRENT.LONG_TERM_BORROWING.MORTGAGE', '주택담보대출', 'LIABILITY.NON_CURRENT.LONG_TERM_BORROWING', 'COMMON', 2211),
  _Seed('EQUITY_TYPE', 'LIABILITY.NON_CURRENT.LONG_TERM_BORROWING.PERSONAL_LOAN', '신용대출(장기)', 'LIABILITY.NON_CURRENT.LONG_TERM_BORROWING', 'COMMON', 2212),
  _Seed('EQUITY_TYPE', 'LIABILITY.NON_CURRENT.LONG_TERM_BORROWING.STUDENT_LOAN', '학자금대출', 'LIABILITY.NON_CURRENT.LONG_TERM_BORROWING', 'COMMON', 2213),
  _Seed('EQUITY_TYPE', 'LIABILITY.NON_CURRENT.LONG_TERM_BORROWING.BOND', '사채', 'LIABILITY.NON_CURRENT.LONG_TERM_BORROWING', 'COMMON', 2214),
  _Seed('EQUITY_TYPE', 'LIABILITY.NON_CURRENT.RETIREMENT_BENEFIT', '퇴직급여부채', 'LIABILITY.NON_CURRENT', 'COMMON', 222),
  _Seed('EQUITY_TYPE', 'LIABILITY.NON_CURRENT.PROVISION', '비유동충당부채', 'LIABILITY.NON_CURRENT', 'COMMON', 223),
  _Seed('EQUITY_TYPE', 'LIABILITY.NON_CURRENT.DEFERRED_TAX_LIABILITY', '이연법인세부채', 'LIABILITY.NON_CURRENT', 'COMMON', 224),
  _Seed('EQUITY_TYPE', 'LIABILITY.NON_CURRENT.LEASE_DEPOSIT_RECEIVED', '임대보증금', 'LIABILITY.NON_CURRENT', 'COMMON', 225),
  _Seed('EQUITY_TYPE', 'LIABILITY.NON_CURRENT.OTHER', '기타비유동부채', 'LIABILITY.NON_CURRENT', 'COMMON', 226),

  // --- EQUITY (자본) ---
  _Seed('EQUITY_TYPE', 'EQUITY', '자본', null, 'COMMON', 300),
  _Seed('EQUITY_TYPE', 'EQUITY.CAPITAL', '자본금', 'EQUITY', 'COMMON', 310),
  _Seed('EQUITY_TYPE', 'EQUITY.CAPITAL_SURPLUS', '자본잉여금', 'EQUITY', 'COMMON', 315),
  _Seed('EQUITY_TYPE', 'EQUITY.RETAINED', '이익잉여금', 'EQUITY', 'COMMON', 320),
  // L4: 이익잉여금 5종
  _Seed('EQUITY_TYPE', 'EQUITY.RETAINED.LEGAL_RESERVE', '법정적립금', 'EQUITY.RETAINED', 'COMMON', 3201),
  _Seed('EQUITY_TYPE', 'EQUITY.RETAINED.VOLUNTARY_RESERVE', '임의적립금', 'EQUITY.RETAINED', 'COMMON', 3202),
  _Seed('EQUITY_TYPE', 'EQUITY.RETAINED.REVALUATION', '재평가차액', 'EQUITY.RETAINED', 'COMMON', 3203),
  _Seed('EQUITY_TYPE', 'EQUITY.RETAINED.UNAPPROPRIATED', '미처분이익잉여금', 'EQUITY.RETAINED', 'COMMON', 3204),
  _Seed('EQUITY_TYPE', 'EQUITY.RETAINED.ACTUARIAL', '보험수리적손익', 'EQUITY.RETAINED', 'COMMON', 3205),
  _Seed('EQUITY_TYPE', 'EQUITY.OTHER', '기타자본', 'EQUITY', 'COMMON', 330),
  // L4: 기타자본 하위
  _Seed('EQUITY_TYPE', 'EQUITY.OTHER.TREASURY_STOCK', '자기주식', 'EQUITY.OTHER', 'COMMON', 3301),
  _Seed('EQUITY_TYPE', 'EQUITY.OTHER.STOCK_OPTIONS', '주식선택권', 'EQUITY.OTHER', 'COMMON', 3302),
  // v2.0: OCI 누계액 (Grace §12.1a에서 정의한 P1 5종)
  _Seed('EQUITY_TYPE', 'EQUITY.OCI_ACCUMULATED', '기타포괄손익누계액', 'EQUITY', 'COMMON', 340),
  _Seed('EQUITY_TYPE', 'EQUITY.OCI_ACCUMULATED.FVOCI_VALUATION', 'FVOCI금융자산평가손익', 'EQUITY.OCI_ACCUMULATED', 'COMMON', 3401),
  _Seed('EQUITY_TYPE', 'EQUITY.OCI_ACCUMULATED.FOREIGN_CURRENCY_TRANSLATION', '해외사업환산손익', 'EQUITY.OCI_ACCUMULATED', 'COMMON', 3402),
  _Seed('EQUITY_TYPE', 'EQUITY.OCI_ACCUMULATED.EQUITY_METHOD_CHANGES', '지분법자본변동', 'EQUITY.OCI_ACCUMULATED', 'COMMON', 3403),
  _Seed('EQUITY_TYPE', 'EQUITY.OCI_ACCUMULATED.ACTUARIAL', '보험수리적손익', 'EQUITY.OCI_ACCUMULATED', 'COMMON', 3404),
  _Seed('EQUITY_TYPE', 'EQUITY.OCI_ACCUMULATED.OTHER_OCI', '기타OCI', 'EQUITY.OCI_ACCUMULATED', 'COMMON', 3405),
  _Seed('EQUITY_TYPE', 'EQUITY.MINORITY_INTEREST', '비지배지분', 'EQUITY', 'COMMON', 350),

  // --- REVENUE (수익) ---
  _Seed('EQUITY_TYPE', 'REVENUE', '수익', null, 'COMMON', 400),
  _Seed('EQUITY_TYPE', 'REVENUE.OPERATING', '영업수익', 'REVENUE', 'COMMON', 410),
  // L4: 영업수익 하위
  _Seed('EQUITY_TYPE', 'REVENUE.OPERATING.SALARY', '급여소득', 'REVENUE.OPERATING', 'COMMON', 4101),
  _Seed('EQUITY_TYPE', 'REVENUE.OPERATING.SALARY.BASE', '기본급', 'REVENUE.OPERATING.SALARY', 'COMMON', 41011),
  _Seed('EQUITY_TYPE', 'REVENUE.OPERATING.SALARY.BONUS', '상여금', 'REVENUE.OPERATING.SALARY', 'COMMON', 41012),
  _Seed('EQUITY_TYPE', 'REVENUE.OPERATING.BUSINESS', '사업소득', 'REVENUE.OPERATING', 'COMMON', 4102),
  _Seed('EQUITY_TYPE', 'REVENUE.OPERATING.BUSINESS.SERVICE', '용역매출', 'REVENUE.OPERATING.BUSINESS', 'COMMON', 41021),
  _Seed('EQUITY_TYPE', 'REVENUE.OPERATING.BUSINESS.GOODS', '상품매출', 'REVENUE.OPERATING.BUSINESS', 'COMMON', 41022),
  _Seed('EQUITY_TYPE', 'REVENUE.OPERATING.RENTAL', '임대수익', 'REVENUE.OPERATING', 'COMMON', 4103),
  _Seed('EQUITY_TYPE', 'REVENUE.OPERATING.PENSION', '연금수령', 'REVENUE.OPERATING', 'COMMON', 4104),
  _Seed('EQUITY_TYPE', 'REVENUE.FINANCIAL', '금융수익', 'REVENUE', 'COMMON', 420),
  // L4: 금융수익 하위
  _Seed('EQUITY_TYPE', 'REVENUE.FINANCIAL.INTEREST', '이자수익', 'REVENUE.FINANCIAL', 'COMMON', 4201),
  _Seed('EQUITY_TYPE', 'REVENUE.FINANCIAL.INTEREST.DEPOSIT', '예금이자', 'REVENUE.FINANCIAL.INTEREST', 'COMMON', 42011),
  _Seed('EQUITY_TYPE', 'REVENUE.FINANCIAL.INTEREST.BOND', '채권이자', 'REVENUE.FINANCIAL.INTEREST', 'COMMON', 42012),
  _Seed('EQUITY_TYPE', 'REVENUE.FINANCIAL.DIVIDEND', '배당수익', 'REVENUE.FINANCIAL', 'COMMON', 4202),
  _Seed('EQUITY_TYPE', 'REVENUE.FINANCIAL.FX_GAIN', '외환차익', 'REVENUE.FINANCIAL', 'COMMON', 4203),
  _Seed('EQUITY_TYPE', 'REVENUE.FINANCIAL.FX_TRANSLATION_GAIN', '외화환산이익', 'REVENUE.FINANCIAL', 'COMMON', 4204),
  _Seed('EQUITY_TYPE', 'REVENUE.FINANCIAL.FVTPL_GAIN', 'FVTPL금융자산평가이익', 'REVENUE.FINANCIAL', 'COMMON', 4205),
  _Seed('EQUITY_TYPE', 'REVENUE.INVESTMENT', '투자수익', 'REVENUE', 'COMMON', 430),
  // L4: 투자수익 하위
  _Seed('EQUITY_TYPE', 'REVENUE.INVESTMENT.DISPOSAL_GAIN', '처분이익', 'REVENUE.INVESTMENT', 'COMMON', 4301),
  _Seed('EQUITY_TYPE', 'REVENUE.INVESTMENT.EQUITY_METHOD_GAIN', '지분법이익', 'REVENUE.INVESTMENT', 'COMMON', 4302),
  _Seed('EQUITY_TYPE', 'REVENUE.OTHER', '기타수익', 'REVENUE', 'COMMON', 440),
  _Seed('EQUITY_TYPE', 'REVENUE.OTHER.MISCELLANEOUS', '잡이익', 'REVENUE.OTHER', 'COMMON', 4401),

  // --- EXPENSE (비용) ---
  _Seed('EQUITY_TYPE', 'EXPENSE', '비용', null, 'COMMON', 500),
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING', '생활비', 'EXPENSE', 'COMMON', 510),
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.FOOD', '식비', 'EXPENSE.LIVING', 'COMMON', 511),
  // L4: 식비 하위
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.FOOD.GROCERY', '식료품', 'EXPENSE.LIVING.FOOD', 'COMMON', 5111),
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.FOOD.DINING_OUT', '외식', 'EXPENSE.LIVING.FOOD', 'COMMON', 5112),
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.FOOD.DELIVERY', '배달', 'EXPENSE.LIVING.FOOD', 'COMMON', 5113),
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.FOOD.SNACK', '간식/음료', 'EXPENSE.LIVING.FOOD', 'COMMON', 5114),
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.TRANSPORT', '교통비', 'EXPENSE.LIVING', 'COMMON', 512),
  // L4: 교통비 하위
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.TRANSPORT.PUBLIC', '대중교통', 'EXPENSE.LIVING.TRANSPORT', 'COMMON', 5121),
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.TRANSPORT.TAXI', '택시', 'EXPENSE.LIVING.TRANSPORT', 'COMMON', 5122),
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.TRANSPORT.FUEL', '주유', 'EXPENSE.LIVING.TRANSPORT', 'COMMON', 5123),
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.TRANSPORT.PARKING', '주차', 'EXPENSE.LIVING.TRANSPORT', 'COMMON', 5124),
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.TRANSPORT.MAINTENANCE', '차량유지', 'EXPENSE.LIVING.TRANSPORT', 'COMMON', 5125),
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.TELECOM', '통신비', 'EXPENSE.LIVING', 'COMMON', 513),
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.TELECOM.MOBILE', '휴대폰', 'EXPENSE.LIVING.TELECOM', 'COMMON', 5131),
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.TELECOM.INTERNET', '인터넷', 'EXPENSE.LIVING.TELECOM', 'COMMON', 5132),
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.HOUSING', '주거비', 'EXPENSE.LIVING', 'COMMON', 514),
  // L4: 주거비 하위
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.HOUSING.RENT', '월세', 'EXPENSE.LIVING.HOUSING', 'COMMON', 5141),
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.HOUSING.MAINTENANCE_FEE', '관리비', 'EXPENSE.LIVING.HOUSING', 'COMMON', 5142),
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.HOUSING.ELECTRICITY', '전기료', 'EXPENSE.LIVING.HOUSING', 'COMMON', 5143),
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.HOUSING.GAS', '가스료', 'EXPENSE.LIVING.HOUSING', 'COMMON', 5144),
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.HOUSING.WATER', '수도료', 'EXPENSE.LIVING.HOUSING', 'COMMON', 5145),
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.MEDICAL', '의료비', 'EXPENSE.LIVING', 'COMMON', 515),
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.MEDICAL.HOSPITAL', '병원', 'EXPENSE.LIVING.MEDICAL', 'COMMON', 5151),
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.MEDICAL.PHARMACY', '약국', 'EXPENSE.LIVING.MEDICAL', 'COMMON', 5152),
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.MEDICAL.INSURANCE', '건강보험', 'EXPENSE.LIVING.MEDICAL', 'COMMON', 5153),
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.EDUCATION', '교육비', 'EXPENSE.LIVING', 'COMMON', 516),
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.EDUCATION.TUITION', '등록금', 'EXPENSE.LIVING.EDUCATION', 'COMMON', 5161),
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.EDUCATION.ACADEMY', '학원비', 'EXPENSE.LIVING.EDUCATION', 'COMMON', 5162),
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.EDUCATION.BOOKS', '교재비', 'EXPENSE.LIVING.EDUCATION', 'COMMON', 5163),
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.CLOTHING', '의류비', 'EXPENSE.LIVING', 'COMMON', 517),
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.CULTURE', '문화여가비', 'EXPENSE.LIVING', 'COMMON', 518),
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.CULTURE.ENTERTAINMENT', '오락', 'EXPENSE.LIVING.CULTURE', 'COMMON', 5181),
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.CULTURE.TRAVEL', '여행', 'EXPENSE.LIVING.CULTURE', 'COMMON', 5182),
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.CULTURE.SUBSCRIPTION', '구독', 'EXPENSE.LIVING.CULTURE', 'COMMON', 5183),
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.BEAUTY', '미용비', 'EXPENSE.LIVING', 'COMMON', 519),
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.PET', '반려동물', 'EXPENSE.LIVING', 'COMMON', 5191),
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.SOCIAL', '경조사비', 'EXPENSE.LIVING', 'COMMON', 5192),
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.INSURANCE_PREMIUM', '보험료', 'EXPENSE.LIVING', 'COMMON', 5193),
  _Seed('EQUITY_TYPE', 'EXPENSE.LIVING.OTHER', '기타생활비', 'EXPENSE.LIVING', 'COMMON', 5199),
  _Seed('EQUITY_TYPE', 'EXPENSE.OPERATING', '영업비용', 'EXPENSE', 'COMMON', 520),
  // L4: 영업비용 하위 (SGA)
  _Seed('EQUITY_TYPE', 'EXPENSE.OPERATING.SALARY', '급여', 'EXPENSE.OPERATING', 'COMMON', 5201),
  _Seed('EQUITY_TYPE', 'EXPENSE.OPERATING.RETIREMENT_BENEFIT', '퇴직급여', 'EXPENSE.OPERATING', 'COMMON', 5202),
  _Seed('EQUITY_TYPE', 'EXPENSE.OPERATING.FRINGE_BENEFIT', '복리후생비', 'EXPENSE.OPERATING', 'COMMON', 5203),
  _Seed('EQUITY_TYPE', 'EXPENSE.OPERATING.TRAVEL', '여비교통비', 'EXPENSE.OPERATING', 'COMMON', 5204),
  _Seed('EQUITY_TYPE', 'EXPENSE.OPERATING.ENTERTAINMENT', '접대비', 'EXPENSE.OPERATING', 'COMMON', 5205),
  _Seed('EQUITY_TYPE', 'EXPENSE.OPERATING.BAD_DEBT', '대손상각비', 'EXPENSE.OPERATING', 'COMMON', 5206),
  _Seed('EQUITY_TYPE', 'EXPENSE.OPERATING.RENT', '지급임차료', 'EXPENSE.OPERATING', 'COMMON', 5207),
  _Seed('EQUITY_TYPE', 'EXPENSE.OPERATING.INSURANCE', '보험료', 'EXPENSE.OPERATING', 'COMMON', 5208),
  _Seed('EQUITY_TYPE', 'EXPENSE.OPERATING.COMMISSION', '지급수수료', 'EXPENSE.OPERATING', 'COMMON', 5209),
  _Seed('EQUITY_TYPE', 'EXPENSE.OPERATING.OUTSOURCING', '외주용역비', 'EXPENSE.OPERATING', 'COMMON', 5210),
  _Seed('EQUITY_TYPE', 'EXPENSE.OPERATING.MARKETING', '광고선전비', 'EXPENSE.OPERATING', 'COMMON', 5211),
  _Seed('EQUITY_TYPE', 'EXPENSE.OPERATING.SUPPLIES', '소모품비', 'EXPENSE.OPERATING', 'COMMON', 5212),
  _Seed('EQUITY_TYPE', 'EXPENSE.OPERATING.OTHER_SGA', '기타판관비', 'EXPENSE.OPERATING', 'COMMON', 5213),
  _Seed('EQUITY_TYPE', 'EXPENSE.COGS', '매출원가', 'EXPENSE', 'COMMON', 525),
  // L4: 매출원가 하위
  _Seed('EQUITY_TYPE', 'EXPENSE.COGS.MATERIAL', '원재료비', 'EXPENSE.COGS', 'COMMON', 5251),
  _Seed('EQUITY_TYPE', 'EXPENSE.COGS.LABOR', '직접노무비', 'EXPENSE.COGS', 'COMMON', 5252),
  _Seed('EQUITY_TYPE', 'EXPENSE.COGS.OVERHEAD', '제조간접비', 'EXPENSE.COGS', 'COMMON', 5253),
  _Seed('EQUITY_TYPE', 'EXPENSE.FINANCIAL', '금융비용', 'EXPENSE', 'COMMON', 530),
  // L4: 금융비용 하위
  _Seed('EQUITY_TYPE', 'EXPENSE.FINANCIAL.INTEREST', '이자비용', 'EXPENSE.FINANCIAL', 'COMMON', 5301),
  _Seed('EQUITY_TYPE', 'EXPENSE.FINANCIAL.FX_LOSS', '외환차손', 'EXPENSE.FINANCIAL', 'COMMON', 5302),
  _Seed('EQUITY_TYPE', 'EXPENSE.FINANCIAL.FX_TRANSLATION_LOSS', '외화환산손실', 'EXPENSE.FINANCIAL', 'COMMON', 5303),
  _Seed('EQUITY_TYPE', 'EXPENSE.FINANCIAL.FVTPL_LOSS', 'FVTPL금융자산평가손실', 'EXPENSE.FINANCIAL', 'COMMON', 5304),
  _Seed('EQUITY_TYPE', 'EXPENSE.DEPRECIATION', '감가상각비', 'EXPENSE', 'COMMON', 540),
  // L4: 감가상각 하위
  _Seed('EQUITY_TYPE', 'EXPENSE.DEPRECIATION.TANGIBLE', '유형자산상각비', 'EXPENSE.DEPRECIATION', 'COMMON', 5401),
  _Seed('EQUITY_TYPE', 'EXPENSE.DEPRECIATION.INTANGIBLE', '무형자산상각비', 'EXPENSE.DEPRECIATION', 'COMMON', 5402),
  _Seed('EQUITY_TYPE', 'EXPENSE.DEPRECIATION.INVESTMENT_PROPERTY', '투자부동산상각비', 'EXPENSE.DEPRECIATION', 'COMMON', 5403),
  _Seed('EQUITY_TYPE', 'EXPENSE.TAX', '세금과공과', 'EXPENSE', 'COMMON', 550),
  // L4: 세금 하위
  _Seed('EQUITY_TYPE', 'EXPENSE.TAX.INCOME_TAX', '법인세(소득세)비용', 'EXPENSE.TAX', 'COMMON', 5501),
  _Seed('EQUITY_TYPE', 'EXPENSE.TAX.PROPERTY_TAX', '재산세', 'EXPENSE.TAX', 'COMMON', 5502),
  _Seed('EQUITY_TYPE', 'EXPENSE.TAX.OTHER_TAX', '기타세금', 'EXPENSE.TAX', 'COMMON', 5503),
  _Seed('EQUITY_TYPE', 'EXPENSE.OTHER', '기타비용', 'EXPENSE', 'COMMON', 560),
  // L4: 기타비용 하위
  _Seed('EQUITY_TYPE', 'EXPENSE.OTHER.DONATION', '기부금', 'EXPENSE.OTHER', 'COMMON', 5601),
  _Seed('EQUITY_TYPE', 'EXPENSE.OTHER.PENALTY', '벌과금', 'EXPENSE.OTHER', 'COMMON', 5602),
  _Seed('EQUITY_TYPE', 'EXPENSE.OTHER.DISPOSAL_LOSS', '처분손실', 'EXPENSE.OTHER', 'COMMON', 5603),
  _Seed('EQUITY_TYPE', 'EXPENSE.OTHER.IMPAIRMENT', '자산손상차손', 'EXPENSE.OTHER', 'COMMON', 5604),
  _Seed('EQUITY_TYPE', 'EXPENSE.OTHER.EQUITY_METHOD_LOSS', '지분법손실', 'EXPENSE.OTHER', 'COMMON', 5605),
  _Seed('EQUITY_TYPE', 'EXPENSE.OTHER.MISCELLANEOUS', '잡손실', 'EXPENSE.OTHER', 'COMMON', 5606),
];

// =============================================================================
// 2. LIQUIDITY (유동성)
// =============================================================================

const List<_Seed> _kLiquiditySeeds = [
  _Seed('LIQUIDITY', 'CURRENT', '유동', null, 'COMMON', 10),
  _Seed('LIQUIDITY', 'NON_CURRENT', '비유동', null, 'COMMON', 20),
];

// =============================================================================
// 3. ASSET_TYPE (자산종류)
// =============================================================================

const List<_Seed> _kAssetTypeSeeds = [
  _Seed('ASSET_TYPE', 'CASH', '현금성자산', null, 'COMMON', 10),
  _Seed('ASSET_TYPE', 'SHORT_TERM_FINANCIAL', '단기금융자산', null, 'COMMON', 20),
  _Seed('ASSET_TYPE', 'RECEIVABLE', '매출채권', null, 'COMMON', 30),
  _Seed('ASSET_TYPE', 'PREPAID', '선급금', null, 'COMMON', 40),
  _Seed('ASSET_TYPE', 'INVENTORY', '재고자산', null, 'COMMON', 50),
  _Seed('ASSET_TYPE', 'INVESTMENT', '투자자산', null, 'COMMON', 60),
  _Seed('ASSET_TYPE', 'TANGIBLE', '유형자산', null, 'COMMON', 70),
  _Seed('ASSET_TYPE', 'INTANGIBLE', '무형자산', null, 'COMMON', 80),
  _Seed('ASSET_TYPE', 'OTHER', '기타자산', null, 'COMMON', 90),
];

// =============================================================================
// 4. ACTIVITY_TYPE (활동구분) — 가계/기업 공용
// =============================================================================

const List<_Seed> _kActivityTypeSeeds = [
  // 가계/기업 공용
  _Seed('ACTIVITY_TYPE', 'HOUSEHOLD', '가계활동', null, 'COMMON', 10),
  _Seed('ACTIVITY_TYPE', 'HOUSEHOLD.CONSUMPTION', '소비', 'HOUSEHOLD', 'COMMON', 11),
  _Seed('ACTIVITY_TYPE', 'HOUSEHOLD.SAVING', '저축', 'HOUSEHOLD', 'COMMON', 12),
  _Seed('ACTIVITY_TYPE', 'OPERATING', '영업활동', null, 'COMMON', 20),
  _Seed('ACTIVITY_TYPE', 'OPERATING.SALES', '매출관련', 'OPERATING', 'COMMON', 21),
  _Seed('ACTIVITY_TYPE', 'OPERATING.PURCHASE', '매입관련', 'OPERATING', 'COMMON', 22),
  _Seed('ACTIVITY_TYPE', 'INVESTING', '투자활동', null, 'COMMON', 30),
  _Seed('ACTIVITY_TYPE', 'INVESTING.TANGIBLE', '유형자산취득처분', 'INVESTING', 'COMMON', 31),
  _Seed('ACTIVITY_TYPE', 'INVESTING.FINANCIAL', '금융자산취득처분', 'INVESTING', 'COMMON', 32),
  _Seed('ACTIVITY_TYPE', 'FINANCING', '재무활동', null, 'COMMON', 40),
  _Seed('ACTIVITY_TYPE', 'FINANCING.BORROWING', '차입금', 'FINANCING', 'COMMON', 41),
  _Seed('ACTIVITY_TYPE', 'FINANCING.DIVIDEND', '배당금지급', 'FINANCING', 'COMMON', 42),
];

// =============================================================================
// 5. INCOME_TYPE (소득유형) — 한국 소득세법 8종
// =============================================================================

const List<_Seed> _kIncomeTypeSeeds = [
  _Seed('INCOME_TYPE', 'INTEREST', '이자소득', null, 'COMMON', 10),
  _Seed('INCOME_TYPE', 'INTEREST.COMPREHENSIVE', '종합과세', 'INTEREST', 'COMMON', 11),
  _Seed('INCOME_TYPE', 'INTEREST.SEPARATE', '분리과세', 'INTEREST', 'COMMON', 12),
  _Seed('INCOME_TYPE', 'DIVIDEND', '배당소득', null, 'COMMON', 20),
  _Seed('INCOME_TYPE', 'DIVIDEND.COMPREHENSIVE', '종합과세', 'DIVIDEND', 'COMMON', 21),
  _Seed('INCOME_TYPE', 'DIVIDEND.SEPARATE', '분리과세', 'DIVIDEND', 'COMMON', 22),
  _Seed('INCOME_TYPE', 'DIVIDEND.GROSSUP', '종합과세(Gross-up)', 'DIVIDEND', 'COMMON', 23),
  _Seed('INCOME_TYPE', 'BUSINESS', '사업소득', null, 'COMMON', 30),
  _Seed('INCOME_TYPE', 'EMPLOYMENT', '근로소득', null, 'COMMON', 40),
  _Seed('INCOME_TYPE', 'PENSION', '연금소득', null, 'COMMON', 50),
  _Seed('INCOME_TYPE', 'CAPITAL_GAINS', '양도소득', null, 'COMMON', 60),
  _Seed('INCOME_TYPE', 'RETIREMENT', '퇴직소득', null, 'COMMON', 70),
  _Seed('INCOME_TYPE', 'OTHER', '기타소득', null, 'COMMON', 80),
];

// =============================================================================
// 6. 정부회계 확장 (entity_type = 'GOVERNMENT')
// =============================================================================

const List<_Seed> _kGovernmentSeeds = [
  // 자기자본성: 자본 → 순자산 대체
  _Seed('EQUITY_TYPE', 'NET_ASSETS', '순자산', null, 'GOVERNMENT', 300),
  _Seed('EQUITY_TYPE', 'NET_ASSETS.ACCUMULATED', '순자산변동누계', 'NET_ASSETS', 'GOVERNMENT', 310),

  // 활동구분: 경상/자본/세입/세출
  _Seed('ACTIVITY_TYPE', 'RECURRENT', '경상적지출', null, 'GOVERNMENT', 10),
  _Seed('ACTIVITY_TYPE', 'RECURRENT.PERSONNEL', '인건비', 'RECURRENT', 'GOVERNMENT', 11),
  _Seed('ACTIVITY_TYPE', 'RECURRENT.GOODS', '물건비', 'RECURRENT', 'GOVERNMENT', 12),
  _Seed('ACTIVITY_TYPE', 'RECURRENT.TRANSFER', '이전경비', 'RECURRENT', 'GOVERNMENT', 13),
  _Seed('ACTIVITY_TYPE', 'CAPITAL_EXPENDITURE', '자본적지출', null, 'GOVERNMENT', 20),
  _Seed('ACTIVITY_TYPE', 'CAPITAL_EXPENDITURE.FACILITY', '시설비', 'CAPITAL_EXPENDITURE', 'GOVERNMENT', 21),
  _Seed('ACTIVITY_TYPE', 'REVENUE_GOV', '세입', null, 'GOVERNMENT', 30),
  _Seed('ACTIVITY_TYPE', 'REVENUE_GOV.TAX', '세수입', 'REVENUE_GOV', 'GOVERNMENT', 31),
  _Seed('ACTIVITY_TYPE', 'REVENUE_GOV.NON_TAX', '세외수입', 'REVENUE_GOV', 'GOVERNMENT', 32),
  _Seed('ACTIVITY_TYPE', 'REVENUE_GOV.SUBSIDY', '보조금', 'REVENUE_GOV', 'GOVERNMENT', 33),
];

// =============================================================================
// 공개 API — DB 초기화 시 호출
// =============================================================================

/// 전체 시드 데이터 목록 (DB batch insert용)
///
/// 반환 형식: List<Map<String, dynamic>> — Drift의 batch insert와 호환.
/// 각 Map의 키: dimensionType, code, name, parentCode, entityType, sortOrder, isSystem
List<Map<String, dynamic>> getAllDimensionValueSeeds() {
  final List<_Seed> listAllSeeds = [
    ..._kEquityTypeSeeds,
    ..._kLiquiditySeeds,
    ..._kAssetTypeSeeds,
    ..._kActivityTypeSeeds,
    ..._kIncomeTypeSeeds,
    ..._kGovernmentSeeds,
  ];

  return listAllSeeds.map((seed) {
    return {
      'dimensionType': seed.type,
      'code': seed.code,
      'name': seed.name,
      'parentCode': seed.parentCode,
      'entityType': seed.entityType,
      'sortOrder': seed.sortOrder,
      'isSystem': true,
    };
  }).toList();
}

/// 특정 entity_type의 시드만 필터 (가계/기업: 'COMMON', 정부: 'GOVERNMENT')
List<Map<String, dynamic>> getDimensionValueSeedsByEntityType(String entityType) {
  return getAllDimensionValueSeeds()
      .where((map) => map['entityType'] == entityType || map['entityType'] == 'COMMON')
      .toList();
}

/// 시드 데이터 통계 (검증용)
Map<String, int> getSeedStatistics() {
  final listAll = getAllDimensionValueSeeds();
  final Map<String, int> mapStats = {};
  for (final map in listAll) {
    final String type = map['dimensionType'] as String;
    mapStats[type] = (mapStats[type] ?? 0) + 1;
  }
  mapStats['TOTAL'] = listAll.length;
  return mapStats;
}
